// Generated from the ISO 4217 currency list published 2026-01-01.
// Codes that define no subunit are left out. Regenerate with currency-table.codegen.mjs.

export const ISO_CURRENCY_TABLE = {
    AED: { numericCode: '784', minorUnits: 2, name: 'United Arab Emirates Dirham', shortName: 'UAE Dirham' },
    AFN: { numericCode: '971', minorUnits: 2, name: 'Afghan Afghani', shortName: 'Afghani' },
    ALL: { numericCode: '008', minorUnits: 2, name: 'Albanian Lek', shortName: 'Lek' },
    AMD: { numericCode: '051', minorUnits: 2, name: 'Armenian Dram', shortName: 'Armenian Dram' },
    AOA: { numericCode: '973', minorUnits: 2, name: 'Angolan Kwanza', shortName: 'Kwanza' },
    ARS: { numericCode: '032', minorUnits: 2, name: 'Argentine Peso', shortName: 'Argentine Peso' },
    AUD: { numericCode: '036', minorUnits: 2, name: 'Australian Dollar', shortName: 'Australian Dollar' },
    AWG: { numericCode: '533', minorUnits: 2, name: 'Aruban Florin', shortName: 'Aruban Florin' },
    AZN: { numericCode: '944', minorUnits: 2, name: 'Azerbaijani Manat', shortName: 'Azerbaijan Manat' },
    BAM: { numericCode: '977', minorUnits: 2, name: 'Bosnia-Herzegovina Convertible Mark', shortName: 'Convertible Mark' },
    BBD: { numericCode: '052', minorUnits: 2, name: 'Barbadian Dollar', shortName: 'Barbados Dollar' },
    BDT: { numericCode: '050', minorUnits: 2, name: 'Bangladeshi Taka', shortName: 'Taka' },
    BHD: { numericCode: '048', minorUnits: 3, name: 'Bahraini Dinar', shortName: 'Bahraini Dinar' },
    BIF: { numericCode: '108', minorUnits: 0, name: 'Burundian Franc', shortName: 'Burundi Franc' },
    BMD: { numericCode: '060', minorUnits: 2, name: 'Bermudan Dollar', shortName: 'Bermudian Dollar' },
    BND: { numericCode: '096', minorUnits: 2, name: 'Brunei Dollar', shortName: 'Brunei Dollar' },
    BOB: { numericCode: '068', minorUnits: 2, name: 'Bolivian Boliviano', shortName: 'Boliviano' },
    BOV: { numericCode: '984', minorUnits: 2, name: 'Bolivian Mvdol', shortName: 'Mvdol' },
    BRL: { numericCode: '986', minorUnits: 2, name: 'Brazilian Real', shortName: 'Brazilian Real' },
    BSD: { numericCode: '044', minorUnits: 2, name: 'Bahamian Dollar', shortName: 'Bahamian Dollar' },
    BTN: { numericCode: '064', minorUnits: 2, name: 'Bhutanese Ngultrum', shortName: 'Ngultrum' },
    BWP: { numericCode: '072', minorUnits: 2, name: 'Botswanan Pula', shortName: 'Pula' },
    BYN: { numericCode: '933', minorUnits: 2, name: 'Belarusian Ruble', shortName: 'Belarusian Ruble' },
    BZD: { numericCode: '084', minorUnits: 2, name: 'Belize Dollar', shortName: 'Belize Dollar' },
    CAD: { numericCode: '124', minorUnits: 2, name: 'Canadian Dollar', shortName: 'Canadian Dollar' },
    CDF: { numericCode: '976', minorUnits: 2, name: 'Congolese Franc', shortName: 'Congolese Franc' },
    CHE: { numericCode: '947', minorUnits: 2, name: 'WIR Euro', shortName: 'WIR Euro' },
    CHF: { numericCode: '756', minorUnits: 2, name: 'Swiss Franc', shortName: 'Swiss Franc' },
    CHW: { numericCode: '948', minorUnits: 2, name: 'WIR Franc', shortName: 'WIR Franc' },
    CLF: { numericCode: '990', minorUnits: 4, name: 'Chilean Unit of Account (UF)', shortName: 'Unidad de Fomento' },
    CLP: { numericCode: '152', minorUnits: 0, name: 'Chilean Peso', shortName: 'Chilean Peso' },
    CNY: { numericCode: '156', minorUnits: 2, name: 'Chinese Yuan', shortName: 'Yuan Renminbi' },
    COP: { numericCode: '170', minorUnits: 2, name: 'Colombian Peso', shortName: 'Colombian Peso' },
    COU: { numericCode: '970', minorUnits: 2, name: 'Colombian Real Value Unit', shortName: 'Unidad de Valor Real' },
    CRC: { numericCode: '188', minorUnits: 2, name: 'Costa Rican Colón', shortName: 'Costa Rican Colon' },
    CUP: { numericCode: '192', minorUnits: 2, name: 'Cuban Peso', shortName: 'Cuban Peso' },
    CVE: { numericCode: '132', minorUnits: 2, name: 'Cape Verdean Escudo', shortName: 'Cabo Verde Escudo' },
    CZK: { numericCode: '203', minorUnits: 2, name: 'Czech Koruna', shortName: 'Czech Koruna' },
    DJF: { numericCode: '262', minorUnits: 0, name: 'Djiboutian Franc', shortName: 'Djibouti Franc' },
    DKK: { numericCode: '208', minorUnits: 2, name: 'Danish Krone', shortName: 'Danish Krone' },
    DOP: { numericCode: '214', minorUnits: 2, name: 'Dominican Peso', shortName: 'Dominican Peso' },
    DZD: { numericCode: '012', minorUnits: 2, name: 'Algerian Dinar', shortName: 'Algerian Dinar' },
    EGP: { numericCode: '818', minorUnits: 2, name: 'Egyptian Pound', shortName: 'Egyptian Pound' },
    ERN: { numericCode: '232', minorUnits: 2, name: 'Eritrean Nakfa', shortName: 'Nakfa' },
    ETB: { numericCode: '230', minorUnits: 2, name: 'Ethiopian Birr', shortName: 'Ethiopian Birr' },
    EUR: { numericCode: '978', minorUnits: 2, name: 'Euro', shortName: 'Euro' },
    FJD: { numericCode: '242', minorUnits: 2, name: 'Fijian Dollar', shortName: 'Fiji Dollar' },
    FKP: { numericCode: '238', minorUnits: 2, name: 'Falkland Islands Pound', shortName: 'Falkland Islands Pound' },
    GBP: { numericCode: '826', minorUnits: 2, name: 'British Pound', shortName: 'Pound Sterling' },
    GEL: { numericCode: '981', minorUnits: 2, name: 'Georgian Lari', shortName: 'Lari' },
    GHS: { numericCode: '936', minorUnits: 2, name: 'Ghanaian Cedi', shortName: 'Ghana Cedi' },
    GIP: { numericCode: '292', minorUnits: 2, name: 'Gibraltar Pound', shortName: 'Gibraltar Pound' },
    GMD: { numericCode: '270', minorUnits: 2, name: 'Gambian Dalasi', shortName: 'Dalasi' },
    GNF: { numericCode: '324', minorUnits: 0, name: 'Guinean Franc', shortName: 'Guinean Franc' },
    GTQ: { numericCode: '320', minorUnits: 2, name: 'Guatemalan Quetzal', shortName: 'Quetzal' },
    GYD: { numericCode: '328', minorUnits: 2, name: 'Guyanaese Dollar', shortName: 'Guyana Dollar' },
    HKD: { numericCode: '344', minorUnits: 2, name: 'Hong Kong Dollar', shortName: 'Hong Kong Dollar' },
    HNL: { numericCode: '340', minorUnits: 2, name: 'Honduran Lempira', shortName: 'Lempira' },
    HTG: { numericCode: '332', minorUnits: 2, name: 'Haitian Gourde', shortName: 'Gourde' },
    HUF: { numericCode: '348', minorUnits: 2, name: 'Hungarian Forint', shortName: 'Forint' },
    IDR: { numericCode: '360', minorUnits: 2, name: 'Indonesian Rupiah', shortName: 'Rupiah' },
    ILS: { numericCode: '376', minorUnits: 2, name: 'Israeli New Shekel', shortName: 'New Israeli Sheqel' },
    INR: { numericCode: '356', minorUnits: 2, name: 'Indian Rupee', shortName: 'Indian Rupee' },
    IQD: { numericCode: '368', minorUnits: 3, name: 'Iraqi Dinar', shortName: 'Iraqi Dinar' },
    IRR: { numericCode: '364', minorUnits: 2, name: 'Iranian Rial', shortName: 'Iranian Rial' },
    ISK: { numericCode: '352', minorUnits: 0, name: 'Icelandic Króna', shortName: 'Iceland Krona' },
    JMD: { numericCode: '388', minorUnits: 2, name: 'Jamaican Dollar', shortName: 'Jamaican Dollar' },
    JOD: { numericCode: '400', minorUnits: 3, name: 'Jordanian Dinar', shortName: 'Jordanian Dinar' },
    JPY: { numericCode: '392', minorUnits: 0, name: 'Japanese Yen', shortName: 'Yen' },
    KES: { numericCode: '404', minorUnits: 2, name: 'Kenyan Shilling', shortName: 'Kenyan Shilling' },
    KGS: { numericCode: '417', minorUnits: 2, name: 'Kyrgyz Som', shortName: 'Som' },
    KHR: { numericCode: '116', minorUnits: 2, name: 'Cambodian Riel', shortName: 'Riel' },
    KMF: { numericCode: '174', minorUnits: 0, name: 'Comorian Franc', shortName: 'Comorian Franc' },
    KPW: { numericCode: '408', minorUnits: 2, name: 'North Korean Won', shortName: 'North Korean Won' },
    KRW: { numericCode: '410', minorUnits: 0, name: 'South Korean Won', shortName: 'Won' },
    KWD: { numericCode: '414', minorUnits: 3, name: 'Kuwaiti Dinar', shortName: 'Kuwaiti Dinar' },
    KYD: { numericCode: '136', minorUnits: 2, name: 'Cayman Islands Dollar', shortName: 'Cayman Islands Dollar' },
    KZT: { numericCode: '398', minorUnits: 2, name: 'Kazakhstani Tenge', shortName: 'Tenge' },
    LAK: { numericCode: '418', minorUnits: 2, name: 'Laotian Kip', shortName: 'Lao Kip' },
    LBP: { numericCode: '422', minorUnits: 2, name: 'Lebanese Pound', shortName: 'Lebanese Pound' },
    LKR: { numericCode: '144', minorUnits: 2, name: 'Sri Lankan Rupee', shortName: 'Sri Lanka Rupee' },
    LRD: { numericCode: '430', minorUnits: 2, name: 'Liberian Dollar', shortName: 'Liberian Dollar' },
    LSL: { numericCode: '426', minorUnits: 2, name: 'Lesotho Loti', shortName: 'Loti' },
    LYD: { numericCode: '434', minorUnits: 3, name: 'Libyan Dinar', shortName: 'Libyan Dinar' },
    MAD: { numericCode: '504', minorUnits: 2, name: 'Moroccan Dirham', shortName: 'Moroccan Dirham' },
    MDL: { numericCode: '498', minorUnits: 2, name: 'Moldovan Leu', shortName: 'Moldovan Leu' },
    MGA: { numericCode: '969', minorUnits: 2, name: 'Malagasy Ariary', shortName: 'Malagasy Ariary' },
    MKD: { numericCode: '807', minorUnits: 2, name: 'Macedonian Denar', shortName: 'Denar' },
    MMK: { numericCode: '104', minorUnits: 2, name: 'Myanmar Kyat', shortName: 'Kyat' },
    MNT: { numericCode: '496', minorUnits: 2, name: 'Mongolian Tugrik', shortName: 'Tugrik' },
    MOP: { numericCode: '446', minorUnits: 2, name: 'Macanese Pataca', shortName: 'Pataca' },
    MRU: { numericCode: '929', minorUnits: 2, name: 'Mauritanian Ouguiya', shortName: 'Ouguiya' },
    MUR: { numericCode: '480', minorUnits: 2, name: 'Mauritian Rupee', shortName: 'Mauritius Rupee' },
    MVR: { numericCode: '462', minorUnits: 2, name: 'Maldivian Rufiyaa', shortName: 'Rufiyaa' },
    MWK: { numericCode: '454', minorUnits: 2, name: 'Malawian Kwacha', shortName: 'Malawi Kwacha' },
    MXN: { numericCode: '484', minorUnits: 2, name: 'Mexican Peso', shortName: 'Mexican Peso' },
    MXV: { numericCode: '979', minorUnits: 2, name: 'Mexican Investment Unit', shortName: 'Mexican Unidad de Inversion (UDI)' },
    MYR: { numericCode: '458', minorUnits: 2, name: 'Malaysian Ringgit', shortName: 'Malaysian Ringgit' },
    MZN: { numericCode: '943', minorUnits: 2, name: 'Mozambican Metical', shortName: 'Mozambique Metical' },
    NAD: { numericCode: '516', minorUnits: 2, name: 'Namibian Dollar', shortName: 'Namibia Dollar' },
    NGN: { numericCode: '566', minorUnits: 2, name: 'Nigerian Naira', shortName: 'Naira' },
    NIO: { numericCode: '558', minorUnits: 2, name: 'Nicaraguan Córdoba', shortName: 'Cordoba Oro' },
    NOK: { numericCode: '578', minorUnits: 2, name: 'Norwegian Krone', shortName: 'Norwegian Krone' },
    NPR: { numericCode: '524', minorUnits: 2, name: 'Nepalese Rupee', shortName: 'Nepalese Rupee' },
    NZD: { numericCode: '554', minorUnits: 2, name: 'New Zealand Dollar', shortName: 'New Zealand Dollar' },
    OMR: { numericCode: '512', minorUnits: 3, name: 'Omani Rial', shortName: 'Rial Omani' },
    PAB: { numericCode: '590', minorUnits: 2, name: 'Panamanian Balboa', shortName: 'Balboa' },
    PEN: { numericCode: '604', minorUnits: 2, name: 'Peruvian Sol', shortName: 'Sol' },
    PGK: { numericCode: '598', minorUnits: 2, name: 'Papua New Guinean Kina', shortName: 'Kina' },
    PHP: { numericCode: '608', minorUnits: 2, name: 'Philippine Peso', shortName: 'Philippine Peso' },
    PKR: { numericCode: '586', minorUnits: 2, name: 'Pakistani Rupee', shortName: 'Pakistan Rupee' },
    PLN: { numericCode: '985', minorUnits: 2, name: 'Polish Zloty', shortName: 'Zloty' },
    PYG: { numericCode: '600', minorUnits: 0, name: 'Paraguayan Guarani', shortName: 'Guarani' },
    QAR: { numericCode: '634', minorUnits: 2, name: 'Qatari Riyal', shortName: 'Qatari Rial' },
    RON: { numericCode: '946', minorUnits: 2, name: 'Romanian Leu', shortName: 'Romanian Leu' },
    RSD: { numericCode: '941', minorUnits: 2, name: 'Serbian Dinar', shortName: 'Serbian Dinar' },
    RUB: { numericCode: '643', minorUnits: 2, name: 'Russian Ruble', shortName: 'Russian Ruble' },
    RWF: { numericCode: '646', minorUnits: 0, name: 'Rwandan Franc', shortName: 'Rwanda Franc' },
    SAR: { numericCode: '682', minorUnits: 2, name: 'Saudi Riyal', shortName: 'Saudi Riyal' },
    SBD: { numericCode: '090', minorUnits: 2, name: 'Solomon Islands Dollar', shortName: 'Solomon Islands Dollar' },
    SCR: { numericCode: '690', minorUnits: 2, name: 'Seychellois Rupee', shortName: 'Seychelles Rupee' },
    SDG: { numericCode: '938', minorUnits: 2, name: 'Sudanese Pound', shortName: 'Sudanese Pound' },
    SEK: { numericCode: '752', minorUnits: 2, name: 'Swedish Krona', shortName: 'Swedish Krona' },
    SGD: { numericCode: '702', minorUnits: 2, name: 'Singapore Dollar', shortName: 'Singapore Dollar' },
    SHP: { numericCode: '654', minorUnits: 2, name: 'St. Helena Pound', shortName: 'Saint Helena Pound' },
    SLE: { numericCode: '925', minorUnits: 2, name: 'Sierra Leonean Leone', shortName: 'Leone' },
    SOS: { numericCode: '706', minorUnits: 2, name: 'Somali Shilling', shortName: 'Somali Shilling' },
    SRD: { numericCode: '968', minorUnits: 2, name: 'Surinamese Dollar', shortName: 'Surinam Dollar' },
    SSP: { numericCode: '728', minorUnits: 2, name: 'South Sudanese Pound', shortName: 'South Sudanese Pound' },
    STN: { numericCode: '930', minorUnits: 2, name: 'São Tomé & Príncipe Dobra', shortName: 'Dobra' },
    SVC: { numericCode: '222', minorUnits: 2, name: 'Salvadoran Colón', shortName: 'El Salvador Colon' },
    SYP: { numericCode: '760', minorUnits: 2, name: 'Syrian Pound', shortName: 'Syrian Pound' },
    SZL: { numericCode: '748', minorUnits: 2, name: 'Swazi Lilangeni', shortName: 'Lilangeni' },
    THB: { numericCode: '764', minorUnits: 2, name: 'Thai Baht', shortName: 'Baht' },
    TJS: { numericCode: '972', minorUnits: 2, name: 'Tajikistani Somoni', shortName: 'Somoni' },
    TMT: { numericCode: '934', minorUnits: 2, name: 'Turkmenistani Manat', shortName: 'Turkmenistan New Manat' },
    TND: { numericCode: '788', minorUnits: 3, name: 'Tunisian Dinar', shortName: 'Tunisian Dinar' },
    TOP: { numericCode: '776', minorUnits: 2, name: 'Tongan Paʻanga', shortName: 'Pa’anga' },
    TRY: { numericCode: '949', minorUnits: 2, name: 'Turkish Lira', shortName: 'Turkish Lira' },
    TTD: { numericCode: '780', minorUnits: 2, name: 'Trinidad & Tobago Dollar', shortName: 'Trinidad and Tobago Dollar' },
    TWD: { numericCode: '901', minorUnits: 2, name: 'New Taiwan Dollar', shortName: 'New Taiwan Dollar' },
    TZS: { numericCode: '834', minorUnits: 2, name: 'Tanzanian Shilling', shortName: 'Tanzanian Shilling' },
    UAH: { numericCode: '980', minorUnits: 2, name: 'Ukrainian Hryvnia', shortName: 'Hryvnia' },
    UGX: { numericCode: '800', minorUnits: 0, name: 'Ugandan Shilling', shortName: 'Uganda Shilling' },
    USD: { numericCode: '840', minorUnits: 2, name: 'US Dollar', shortName: 'US Dollar' },
    USN: { numericCode: '997', minorUnits: 2, name: 'US Dollar (Next day)', shortName: 'US Dollar (Next day)' },
    UYI: { numericCode: '940', minorUnits: 0, name: 'Uruguayan Peso (Indexed Units)', shortName: 'Uruguay Peso en Unidades Indexadas (UI)' },
    UYU: { numericCode: '858', minorUnits: 2, name: 'Uruguayan Peso', shortName: 'Peso Uruguayo' },
    UYW: { numericCode: '927', minorUnits: 4, name: 'Uruguayan Nominal Wage Index Unit', shortName: 'Unidad Previsional' },
    UZS: { numericCode: '860', minorUnits: 2, name: 'Uzbekistani Som', shortName: 'Uzbekistan Sum' },
    VED: { numericCode: '926', minorUnits: 2, name: 'Bolívar Soberano', shortName: 'Bolívar Soberano' },
    VES: { numericCode: '928', minorUnits: 2, name: 'Venezuelan Bolívar', shortName: 'Bolívar Soberano' },
    VND: { numericCode: '704', minorUnits: 0, name: 'Vietnamese Dong', shortName: 'Dong' },
    VUV: { numericCode: '548', minorUnits: 0, name: 'Vanuatu Vatu', shortName: 'Vatu' },
    WST: { numericCode: '882', minorUnits: 2, name: 'Samoan Tala', shortName: 'Tala' },
    XAD: { numericCode: '396', minorUnits: 2, name: 'Arab Accounting Dinar', shortName: 'Arab Accounting Dinar' },
    XAF: { numericCode: '950', minorUnits: 0, name: 'Central African CFA Franc', shortName: 'CFA Franc BEAC' },
    XCD: { numericCode: '951', minorUnits: 2, name: 'East Caribbean Dollar', shortName: 'East Caribbean Dollar' },
    XCG: { numericCode: '532', minorUnits: 2, name: 'Caribbean guilder', shortName: 'Caribbean Guilder' },
    XOF: { numericCode: '952', minorUnits: 0, name: 'West African CFA Franc', shortName: 'CFA Franc BCEAO' },
    XPF: { numericCode: '953', minorUnits: 0, name: 'CFP Franc', shortName: 'CFP Franc' },
    YER: { numericCode: '886', minorUnits: 2, name: 'Yemeni Rial', shortName: 'Yemeni Rial' },
    ZAR: { numericCode: '710', minorUnits: 2, name: 'South African Rand', shortName: 'Rand' },
    ZMW: { numericCode: '967', minorUnits: 2, name: 'Zambian Kwacha', shortName: 'Zambian Kwacha' },
    ZWG: { numericCode: '924', minorUnits: 2, name: 'Zimbabwean Gold', shortName: 'Zimbabwe Gold' },
} as const;
